<?php
// File generated by JSWeb Ltd
// Used to communicate security announcements to JSWeb hosted clients
// Version 1.0
// Date: 24/05/5
// Note: If you do not like these messages then please switch xxxx from TRUE to FALSE
//
// Show the following messgae = TRUE

$store=0;
$display=1;
$file = file_get_contents("../includes/configure.php");

if(!strpos($file, "define('ENABLE_SSL', 'true');")) {
//echo "The store side of your website does not appear to have active SSL Certificate protection.<br />";
$store=1;
}

if ((ENABLE_SSL_ADMIN == 'false') OR ($store==1)){// display security warning if not SSL installed in Admin 
	if ($display==1){
	?>
		<div id="jswebalert" style="margin:auto;margin-top:20px; width:600px;">
	<?php }elseif ($display==0){ ?>
		<div id="jswebalert" style="display:none;">
	<?php } ?>
			<span style="font-weight:bold; font-size:16px; color:#900;">JSWEB SECURITY ANNOUNCEMENT</span>(<a href="https://support.jsweb.co.uk/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=232" target="_new"><small>What is this?</small></a>)<br/><br />
<b>Latest Message: 24-May-10</b><br/><br/>
<?php if ($store==1) {// display security warning if not SSL installed in store ?>
<span style="color:#900;">- Your websites, customer side, does not appear to have an SSL Certificate installed.</span>
<br /><br />
<?php } ?>
<?php if (ENABLE_SSL_ADMIN != 'true') {// display security warning if not SSL installed in admin ?>
<span style="color:#900;">- Your websites, admin side, does not appear to have an SSL Certificate installed.</span>
<br /><br />
If you do have an SSL Certificate then <a href="https://support.jsweb.co.uk/index.php?_m=knowledgebase&_a=viewarticle&kbarticleid=232" target="_new">click here for help</a>. If you want to find out more about SSL certificates, click the image below:<br /><br /></span>
<?php } ?>

<a href="http://www.jsweb.co.uk/ssl" target="_new"><img src="https://www.jsweb.co.uk/images/banners/SSL-Admin-Warning.jpg" border="0" /></a>
<br /><br />If you have any problems, please raise a ticket at our <a href="http://support.jsweb.co.uk" target="_blank">Help Desk</a><br /><br />.
<?php }
echo '<br /><br />';

?> 
<!-- <form method="post" action="login.php">
<input type="hidden" value="0" name="display"/>
<input type="submit" name="submit" value="Remove Notification"/> </form> -->
 

</div>

